name: gui
channels:
  - conda-forge
  - cadquery 
dependencies:
  - scipy
  - numpy
  - cadquery=2.1
  - ambiance
  - nptyping=1.4.4
  - plotly
  - pandas
  - pip
  - pip:
    - pyromat
    - streamlit
    - pyvista 
    - stpyvista
    - kaleido
